# 默认的数据库名
database:
  name: story

logging:
  level:
    default: info
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/${database.name}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 666666

forum:
  sensitive: # 敏感词校验相关配置
    enable: true
    deny: hello,fuck,can,shit,asshole,USA,bitch,bbb,cunt,dick,nigger,nigga,fucker,fucking,motherfucker,motherfucking,xxx,x,x,xxx,x,x,xxx,x,x,xxx,x,x,xxx,x,x,xxx, # 自定义的敏感词，英文逗号分割
    allow: good,ok,fun,nice,good,ok,fun,nice,good,ok,fun,nice,good,ok,fun,nice,good,ok,fun,nice,good,ok,fun,nice,good,ok,fun,nice,good,ok,fun,nice,good,ok,fun,nice,good,ok,fun,nice, # 自定义的非敏感词，英文逗号分割
